name: lint_and_type_check
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tyandruff:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - uses: astral-sh/setup-uv@v7

      - name: Ruff lint
        run: uvx ruff check --output-format=github .

      - name: Ruff format
        run: uvx ruff format --check --verbose .

      - name: Type check
        run: uvx ty check .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install eccodes
        run: |
          sudo apt install libeccodes-tools

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest -v
